# Generated by Django 5.2.5 on 2025-09-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_receiverbankaccount_bank_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentitem",
            name="compulsory_for",
            field=models.CharField(
                blank=True, default="All Levels", max_length=100, null=True
            ),
        ),
    ]
