# Generated by Django 5.2.5 on 2025-09-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_paymentitem_compulsory_for"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentitem",
            name="compulsory_for",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
