# Generated by Django 5.2.1 on 2025-06-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_name', models.CharField(default='other', max_length=255, unique=True)),
                ('association_short_name', models.CharField(default='other', max_length=50, unique=True)),
                ('Association_type', models.CharField(choices=[('hall', 'Hall'), ('department', 'Department'), ('faculty', 'Faculty'), ('other', 'Other')], default='Other', max_length=20)),
                ('logo', models.ImageField(default='logos/sharingan.png', upload_to='logos/')),
            ],
        ),
    ]
