# Generated by Django 5.2.4 on 2025-07-06 15:00

import cloudinary.models
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_name', models.CharField(default='other', max_length=255, unique=True)),
                ('association_short_name', models.CharField(default='other', max_length=50, unique=True)),
                ('Association_type', models.CharField(choices=[('hall', 'Hall'), ('department', 'Department'), ('faculty', 'Faculty'), ('other', 'Other')], default='Other', max_length=20)),
                ('logo', cloudinary.models.CloudinaryField(default='DuesPay/default.jpg', max_length=255, validators=[utils.utils.validate_file_type], verbose_name='image')),
            ],
        ),
    ]
