# Generated by Django 5.2.4 on 2025-08-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
