# Generated by Django 5.2.1 on 2025-06-22 00:17

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='logo',
            field=models.FileField(default='logos/sharingan.png', upload_to='logos/', validators=[utils.utils.validate_file_type]),
        ),
    ]
