# Generated by Django 5.2.5 on 2025-08-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("association", "0002_alter_association_association_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="association_type",
            field=models.CharField(
                choices=[
                    ("hall", "Hall"),
                    ("department", "Department"),
                    ("faculty", "Faculty"),
                    ("other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
    ]
