# Generated by Django 5.2.1 on 2025-06-22 00:39

import cloudinary.models
import utils.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_alter_association_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[utils.utils.validate_file_type], verbose_name='image'),
        ),
    ]
