# Generated by Django 5.2.4 on 2025-07-06 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('matric_number', models.CharField(max_length=50)),
                ('faculty', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payers', to='association.association')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('association', 'email'), name='unique_email_per_association'), models.UniqueConstraint(fields=('association', 'phone_number'), name='unique_phone_per_association'), models.UniqueConstraint(fields=('association', 'matric_number'), name='unique_matric_per_association')],
            },
        ),
    ]
