# Generated by Django 5.2.5 on 2025-09-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payer",
            name="level",
            field=models.CharField(
                choices=[
                    ("100", "100 Level"),
                    ("200", "200 Level"),
                    ("300", "300 Level"),
                    ("400", "400 Level"),
                    ("500", "500 Level"),
                    ("600", "600 Level"),
                    ("All Levels", "All Levels"),
                ],
                default="100",
                max_length=20,
            ),
        ),
    ]
