# Generated by Django 5.2.4 on 2025-08-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_alter_session_is_active'),
        ('payers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payer',
            name='unique_email_per_association',
        ),
        migrations.RemoveConstraint(
            model_name='payer',
            name='unique_phone_per_association',
        ),
        migrations.RemoveConstraint(
            model_name='payer',
            name='unique_matric_per_association',
        ),
        migrations.AddConstraint(
            model_name='payer',
            constraint=models.UniqueConstraint(fields=('session', 'email'), name='unique_email_per_session'),
        ),
        migrations.AddConstraint(
            model_name='payer',
            constraint=models.UniqueConstraint(fields=('session', 'phone_number'), name='unique_phone_per_session'),
        ),
        migrations.AddConstraint(
            model_name='payer',
            constraint=models.UniqueConstraint(fields=('session', 'matric_number'), name='unique_matric_per_session'),
        ),
    ]
