# Generated by Django 5.2.1 on 2025-05-31 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=100, unique=True)),
                ('organization_type', models.CharField(choices=[('hall', 'Hall'), ('department', 'Department'), ('faculty', 'Faculty'), ('other', 'Other')], max_length=20)),
                ('faculty', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('hall', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(upload_to='DuesPay/logos/')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='association', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('matric_number', models.CharField(max_length=50)),
                ('faculty', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('hall', models.CharField(blank=True, max_length=100, null=True)),
                ('Association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payers', to='main.association')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('compulsory', 'Compulsory'), ('optional', 'Optional')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='main.association')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiverBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('Association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='main.association')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('proof_of_payment', models.FileField(upload_to='DuesPay/proofs/')),
                ('is_verified', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('Association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.association')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.payer')),
                ('payment_items', models.ManyToManyField(to='main.paymentitem')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='DuesPay/receipts/')),
                ('receipt_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='main.transaction')),
            ],
        ),
    ]
