# Generated by Django 5.2.1 on 2025-05-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentitem',
            old_name='Association',
            new_name='association',
        ),
        migrations.RemoveField(
            model_name='association',
            name='department',
        ),
        migrations.RemoveField(
            model_name='association',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='association',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='association',
            name='organization_type',
        ),
        migrations.RemoveField(
            model_name='association',
            name='space_name',
        ),
        migrations.AddField(
            model_name='association',
            name='Association_type',
            field=models.CharField(choices=[('hall', 'Hall'), ('department', 'Department'), ('faculty', 'Faculty'), ('other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='association',
            name='associaton_name',
            field=models.CharField(default='other', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='association',
            name='associaton_short_name',
            field=models.CharField(default='other', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='logo',
            field=models.ImageField(default='/DuesPay/logos/others.png', upload_to='DuesPay/logos/'),
        ),
    ]
