# Generated by Django 5.2.4 on 2025-07-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Admin User', 'verbose_name_plural': 'Admin Users'},
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(help_text='Email address already registered', max_length=254, unique=True),
        ),
    ]
