# Generated by Django 5.2.1 on 2025-06-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
