# Generated by Django 5.2.1 on 2025-05-21 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payspace',
            name='is_active',
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payspace',
            name='logo',
            field=models.ImageField(upload_to='DuesPay/logos/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='proof_of_payment',
            field=models.FileField(upload_to='DuesPay/proofs/'),
        ),
        migrations.AlterField(
            model_name='transactionreceipt',
            name='pdf_file',
            field=models.FileField(upload_to='DuesPay/receipts/'),
        ),
    ]
