# Generated by Django 5.2.1 on 2025-05-31 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_association_paymentitem_association_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payer',
            old_name='Association',
            new_name='association',
        ),
        migrations.RenameField(
            model_name='receiverbankaccount',
            old_name='Association',
            new_name='association',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Association',
            new_name='association',
        ),
    ]
