# Generated by Django 5.2.1 on 2025-06-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_payer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='payer',
            name='matric_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payer',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payer',
            constraint=models.UniqueConstraint(fields=('association', 'email'), name='unique_email_per_association'),
        ),
        migrations.AddConstraint(
            model_name='payer',
            constraint=models.UniqueConstraint(fields=('association', 'phone_number'), name='unique_phone_per_association'),
        ),
        migrations.AddConstraint(
            model_name='payer',
            constraint=models.UniqueConstraint(fields=('association', 'matric_number'), name='unique_matric_per_association'),
        ),
    ]
