# Generated by Django 5.2.5 on 2025-08-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_platformvba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='username',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='auth_mode',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=10),
        ),
    ]
