# Generated by Django 5.2.5 on 2025-08-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_adminuser_username_adminuser_auth_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
