# Generated by Django 5.2.1 on 2025-05-31 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_association_payer_association_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='associaton_short_name',
            new_name='association_short_name',
        ),
    ]
