# Generated by Django 5.2.5 on 2025-09-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_adminuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="token_version",
            field=models.IntegerField(default=0),
        ),
    ]
