# Generated by Django 5.2.1 on 2025-06-01 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_associaton_short_name_association_association_short_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='associaton_name',
            new_name='association_name',
        ),
    ]
