# Generated by Django 5.2.4 on 2025-07-20 21:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionreceipt',
            name='receipt_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
