# Generated by Django 5.2.5 on 2025-08-15 14:54

import cloudinary.models
import utils.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='proof_of_payment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[utils.utils.validate_file_type], verbose_name='file'),
        ),
    ]
