# Generated by Django 5.2.1 on 2025-06-22 00:17

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='proof_of_payment',
            field=models.FileField(upload_to='DuesPay/proofs/', validators=[utils.utils.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='transactionreceipt',
            name='pdf_file',
            field=models.FileField(upload_to='DuesPay/receipts/', validators=[utils.utils.validate_file_type]),
        ),
    ]
