# Generated by Django 5.2.4 on 2025-07-06 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionreceipt',
            name='pdf_file',
        ),
    ]
