# Generated by Django 5.2.1 on 2025-06-22 00:39

import cloudinary.models
import utils.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_proof_of_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='proof_of_payment',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[utils.utils.validate_file_type], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='transactionreceipt',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[utils.utils.validate_file_type], verbose_name='file'),
        ),
    ]
